CREATE TABLE users (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) UNIQUE,
    password_hash VARCHAR(255),
    full_name VARCHAR(255) NOT NULL,
    phone VARCHAR(50),
    is_guest BOOLEAN NOT NULL DEFAULT FALSE,
    pfp_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE organizers (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    business_name VARCHAR(255) NOT NULL,
    description CLOB,
    website VARCHAR(255),
    logo_url VARCHAR(255),
    verified BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_organizers_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE venues (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    address_line1 VARCHAR(255) NOT NULL,
    city VARCHAR(255) NOT NULL,
    country VARCHAR(2) NOT NULL,
    rating DECIMAL(3, 2),
    cover_photo_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_venues_organizer
        FOREIGN KEY (organizer_id) REFERENCES organizers(id)
);

CREATE TABLE categories (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(255) NOT NULL UNIQUE,
    slug VARCHAR(255) NOT NULL UNIQUE,
    icon_url VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE events (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    organizer_id INT NOT NULL,
    venue_id INT NOT NULL,
    category_id INT NOT NULL,
    title VARCHAR(255) NOT NULL,
    slug VARCHAR(255) NOT NULL UNIQUE,
    description CLOB,
    status VARCHAR(50) NOT NULL,
    start_datetime TIMESTAMP NOT NULL,
    end_datetime TIMESTAMP NOT NULL,
    timezone VARCHAR(100) NOT NULL,
    min_age INT,
    cover_photo_url VARCHAR(255),
    photo_urls CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_events_organizer
        FOREIGN KEY (organizer_id) REFERENCES organizers(id),
    CONSTRAINT fk_events_venue
        FOREIGN KEY (venue_id) REFERENCES venues(id),
    CONSTRAINT fk_events_category
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE ticket_types (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    name VARCHAR(255) NOT NULL,
    description CLOB,
    price DECIMAL(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    quantity_total INT NOT NULL,
    quantity_sold INT NOT NULL DEFAULT 0,
    sale_start TIMESTAMP,
    sale_end TIMESTAMP,
    max_per_order INT NOT NULL DEFAULT 10,
    is_active BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_ticket_types_event
        FOREIGN KEY (event_id) REFERENCES events(id)
);

CREATE TABLE orders (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    guest_email VARCHAR(255),
    guest_name VARCHAR(255),
    guest_phone VARCHAR(50),
    status VARCHAR(50) NOT NULL,
    subtotal DECIMAL(12, 2) NOT NULL,
    fees DECIMAL(12, 2) NOT NULL,
    tax DECIMAL(12, 2) NOT NULL,
    total DECIMAL(12, 2) NOT NULL,
    currency VARCHAR(10) NOT NULL,
    payment_provider VARCHAR(50),
    payment_reference VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_orders_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE tickets (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    event_id INT NOT NULL,
    ticket_type_id INT NOT NULL,
    owner_user_id INT,
    owner_email VARCHAR(255) NOT NULL,
    owner_name VARCHAR(255) NOT NULL,
    price_paid DECIMAL(12, 2) NOT NULL,
    ticket_code VARCHAR(255) NOT NULL UNIQUE,
    qr_code_url VARCHAR(255),
    status VARCHAR(50) NOT NULL,
    checked_in_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_tickets_order
        FOREIGN KEY (order_id) REFERENCES orders(id),
    CONSTRAINT fk_tickets_event
        FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_tickets_ticket_type
        FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(id),
    CONSTRAINT fk_tickets_owner_user
        FOREIGN KEY (owner_user_id) REFERENCES users(id)
);

CREATE TABLE reviews (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT,
    event_id INT,
    venue_id INT,
    rating INT NOT NULL,
    comment CLOB,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_reviews_user
        FOREIGN KEY (user_id) REFERENCES users(id),
    CONSTRAINT fk_reviews_event
        FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_reviews_venue
        FOREIGN KEY (venue_id) REFERENCES venues(id)
);
