CREATE TABLE purchase_confirmation_deliveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id INT NOT NULL,
    order_reference VARCHAR(100) NOT NULL,
    attendee_email VARCHAR(320) NOT NULL,
    event_title VARCHAR(255) NOT NULL,
    event_date_time TIMESTAMP WITH TIME ZONE NOT NULL,
    event_location VARCHAR(255) NOT NULL,
    ticket_quantity INT NOT NULL,
    ticket_lines VARCHAR(4000) NOT NULL,
    order_access_url VARCHAR(2048),
    qr_code_image_url VARCHAR(2048),
    status VARCHAR(255) NOT NULL,
    failure_reason VARCHAR(1000),
    sent_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uk_purchase_confirmation_order_id UNIQUE (order_id)
);
