CREATE TABLE discount_code (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_id INT NOT NULL,
    code VARCHAR(255) NOT NULL,
    type VARCHAR(50) NOT NULL,
    discount_value DECIMAL(12, 2) NOT NULL,
    active BOOLEAN NOT NULL DEFAULT TRUE,
    max_redemptions INT,
    used_count INT NOT NULL DEFAULT 0,
    expires_at TIMESTAMP,
    CONSTRAINT fk_discount_code_event
        FOREIGN KEY (event_id) REFERENCES events(id)
);
