CREATE TABLE purchase_orders (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_number VARCHAR(255),
    event_id INT NOT NULL,
    guest_name VARCHAR(255),
    guest_email VARCHAR(255),
    status VARCHAR(50),
    subtotal DECIMAL(12, 2),
    discount_amount DECIMAL(12, 2),
    total_amount DECIMAL(12, 2),
    discount_code_id BIGINT,
    created_at TIMESTAMP,
    confirmed_at TIMESTAMP,
    CONSTRAINT fk_purchase_orders_event
        FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_purchase_orders_discount_code
        FOREIGN KEY (discount_code_id) REFERENCES discount_code(id)
);

CREATE TABLE order_items (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL,
    ticket_type_id INT NOT NULL,
    ticket_name VARCHAR(255),
    unit_price DECIMAL(12, 2),
    quantity INT NOT NULL,
    line_total DECIMAL(12, 2),
    CONSTRAINT fk_order_items_order
        FOREIGN KEY (order_id) REFERENCES purchase_orders(id),
    CONSTRAINT fk_order_items_ticket_type
        FOREIGN KEY (ticket_type_id) REFERENCES ticket_types(id)
);

CREATE TABLE payment (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    order_id BIGINT NOT NULL UNIQUE,
    method_type VARCHAR(50),
    status VARCHAR(50),
    amount DECIMAL(12, 2),
    provider_reference VARCHAR(255),
    card_last4 VARCHAR(10),
    created_at TIMESTAMP,
    CONSTRAINT fk_payment_order
        FOREIGN KEY (order_id) REFERENCES purchase_orders(id)
);
