CREATE TABLE tags (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    slug VARCHAR(255) NOT NULL UNIQUE,
    label VARCHAR(255) NOT NULL
);

CREATE TABLE event_tags (
    event_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (event_id, tag_id),
    CONSTRAINT fk_event_tags_event
        FOREIGN KEY (event_id) REFERENCES events(id),
    CONSTRAINT fk_event_tags_tag
        FOREIGN KEY (tag_id) REFERENCES tags(id)
);

CREATE TABLE user_preferences (
    id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id INT NOT NULL UNIQUE,
    home_city VARCHAR(255),
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT fk_user_preferences_user
        FOREIGN KEY (user_id) REFERENCES users(id)
);

CREATE TABLE user_preferred_categories (
    preferences_id INT NOT NULL,
    category_id INT NOT NULL,
    PRIMARY KEY (preferences_id, category_id),
    CONSTRAINT fk_upc_prefs
        FOREIGN KEY (preferences_id) REFERENCES user_preferences(id),
    CONSTRAINT fk_upc_cat
        FOREIGN KEY (category_id) REFERENCES categories(id)
);

CREATE TABLE user_preferred_tags (
    preferences_id INT NOT NULL,
    tag_id INT NOT NULL,
    PRIMARY KEY (preferences_id, tag_id),
    CONSTRAINT fk_upt_prefs
        FOREIGN KEY (preferences_id) REFERENCES user_preferences(id),
    CONSTRAINT fk_upt_tag
        FOREIGN KEY (tag_id) REFERENCES tags(id)
);

-- Seed categories used by the recommendation catalog endpoint on first boot.
INSERT INTO categories (name, slug, created_at, updated_at) VALUES
    ('Music', 'music', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Sports', 'sports', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Arts', 'arts', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Technology', 'technology', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    ('Food', 'food', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
