spring:
  application:
    name: event-ticket-system
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: validate
    open-in-view: false
  thymeleaf:
    cache: false
  flyway:
    enabled: true

event-ticket:
  email:
    sender: log
    from-address: no-reply@event-ticket.local
  seed:
    enabled: true
